### ISSUE TITLE
Classloader instead of classpath

### ISSUE THREAD

**Issue by tdurieux** [STAMP-project/testrunner#66]
Hello,

Is it possible to provide a classloader instead of a classpath to execute the tests?
If no, do you think it is technically possible?

Thanks

**Comment by danglotb** [comment]
Hello @tdurieux 

In the API, there is the method in [JUnitXRunner](https://github.com/STAMP-project/testrunner/blob/master/src/main/java/eu/stamp_project/testrunner/runner/JUnit4Runner.java#L45)
```java
public static void run (String[] testClassNames,
                           String[] testMethodNames,
                           List<String> blackList,
                           JUnit4TestResult listener,
                           ClassLoader customClassLoader)
```
Where you can specify your custome classloader.

However, I'm afraid that you may have trouble with versions of loaded artifacts or clash with already loaded classes, unless your classloader is totally clean.

I developed testrunner around the idea that launching a new JVM is the cleanest and safest way to execute tests.

**Comment by tdurieux** [comment]
Thanks a lot @danglotb
